name: Deploy to Kamatera

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove public folder
        run: rm -rf sbox-backend/public
      
      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KAMATERA_HOST }}
          username: ${{ secrets.KAMATERA_USER }}
          key: ${{ secrets.KAMATERA_KEY }}
          source: "sbox-backend/*"
          target: "/var/www/sboxv1"
      
      - name: Run remote commands via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.KAMATERA_HOST }}
          username: ${{ secrets.KAMATERA_USER }}
          key: ${{ secrets.KAMATERA_KEY }}
          script: |
            cd /var/www/sboxv1
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
